sudo: required

dist: trusty

language: generic

services:
    - docker

before_install:
    - docker build -t kademlia ci/travis

script:
    - docker run -v $(pwd):/src kademlia /bin/sh -c 'mkdir /src/build_cov && cd /src/build_cov && ../scripts/generate_coverage_report.sh ..'

after_success:
    # Upload coverage report to coveralls.
    - docker run -v $(pwd):/src kademlia /bin/sh -c 'cd /src && coveralls-lcov build_cov/app_total_stripped.info'
