sudo: false

os:
    - linux

language:
    - cpp

cache:
    directories:
        - ${TRAVIS_BUILD_DIR}/boost_dep

before_install:
    - export CXXFLAGS='-std=c++11'
    - export CXX='g++-5'
    - export CC='gcc-5'

install:
    # lcov from travis packages is quite old.
    - export LCOV_ROOT="${TRAVIS_BUILD_DIR}/lcov_dep"
    - git clone https://github.com/linux-test-project/lcov ${LCOV_ROOT};
    - export PATH="${LCOV_ROOT}/bin:${PATH}"
    - echo 'geninfo_gcov_tool=gcov-5' >> ~/.lcovrc

    - gem install coveralls-lcov

    # Build our own c++11 enabled boost.
    - export BOOST_ROOT="${TRAVIS_BUILD_DIR}/boost_dep"
    - if [ ! -f "${BOOST_ROOT}/INSTALL" ];
      then
        pushd ${BOOST_ROOT};
        wget -qO- http://sourceforge.net/projects/boost/files/boost/1.60.0/boost_1_60_0.tar.bz2 | tar xj --strip-components=1;
        ./bootstrap.sh --with-libraries=system,filesystem,program_options,test;
        ./b2 -q -j`nproc` variant=release link=shared threading=multi toolset=${CC} address-model=64;
        popd;
      fi

script:
    - mkdir build_cov && pushd build_cov
    - ../scripts/generate_coverage_report.sh ..
    - popd

after_success:
    # Upload coverage report to coveralls.
    - coveralls-lcov build_cov/app_total_stripped.info

addons:
    apt:
        sources:
            # This is required to install recent g++.
            - ubuntu-toolchain-r-test

        packages:
            - g++-5
            - realpath
            - cmake
            - libssl-dev
